linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    # Default linters
    - errorlint
    - exhaustive
    - exhaustruct
    - exportloopref
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - godox
    - gofmt
    - goimports
    - gomnd
    - gomodguard
    - gosec
    - gosmopolitan
    - govet
    - mirror
    - musttag
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - wrapcheck

linters-settings:
  exhaustive:
      default-signifies-exhaustive: true
